import json,sys
fr=json.load(open(sys.argv[1]))
T=[
("10th partial, a bit flat: 2nd slightly in.","10.º armónico, un poco bajo: 2.ª ligeramente adentro."),
("12th partial, a bit sharp.","12.º armónico, un poco alto."),
("5th partial, a bit flat: 2nd slightly in.","5.º armónico, un poco bajo: 2.ª ligeramente adentro."),
("5th partial, a bit flat: 3rd slightly in.","5.º armónico, un poco bajo: 3.ª ligeramente adentro."),
("5th partial, a bit flat: 4th slightly in.","5.º armónico, un poco bajo: 4.ª ligeramente adentro."),
("Right ring finger (not the index).","Anular derecho (no el índice)."),
("No right pinky key.","Ninguna llave de meñique derecho."),
("No keys pressed.","Ninguna llave presionada."),
("Right pinky on the low C key (roller).","Meñique derecho en la llave (rodillo) de do grave."),
("Right pinky on the C♯ key.","Meñique derecho en la llave de do♯."),
("C♯/G♯ key pressed with the left pinky.","Llave do♯/sol♯ accionada con el meñique izquierdo."),
("F♯ key on the left only on a standard Boehm clarinet (17 keys).","Llave de fa♯ solo a la izquierda en el clarinete Boehm estándar (17 llaves)."),
("High F♯ key (right hand).","Llave de fa♯ agudo (mano derecha)."),
("Palm D key.","Llave de palma re."),
("Side key = lowest of the 4 trill keys.","Llave lateral = la más baja de las 4 llaves de trino."),
("Sliver key","Llave paleta (sliver)"),
("Like F♯6 but 2nd trill key instead of right ring finger; right pinky optional (stability).","Como fa♯6, pero 2.ª llave de trino en lugar del anular derecho; meñique derecho opcional (estabilidad)."),
("Like low D, but left index up and no pinky.","Como re grave, pero índice izquierdo levantado y sin meñique."),
("Like middle D, but right hand up and pinky on E♭.","Como re medio, pero mano derecha levantada y meñique en mi♭."),
("Left pinky C","Do con meñique izquierdo"),
("Side C","Do lateral"),
("Side C: useful in chromatic B–C passages.","Do lateral: útil en pasajes cromáticos si–do."),
("Basic fingering (right middle finger).","Digitación básica (dedo medio derecho)."),
("Basic fingering (right middle finger). Chromatic alternate with the auxiliary F♯ key (R1 + side key) not shown.","Digitación básica (dedo medio derecho). Variante cromática con la llave auxiliar de fa♯ (R1 + llave lateral) no representada."),
("Left fingering, useful for F–G♯ connections.","Digitación izquierda, útil para enlazar fa–sol♯."),
("\"Fork\" fingering. Chromatic fingering with the right-hand B/F♯ sliver key not shown.","Digitación «de horquilla». Digitación cromática con la llave paleta si/fa♯ derecha no representada."),
("\"Fork\" fingering. A chromatic fingering with the right-hand B/F♯ sliver key exists (not shown).","Digitación «de horquilla». Existe una digitación cromática con la llave paleta si/fa♯ de la mano derecha (no representada)."),
("Low C♯. WFG adds RC; many methods omit it (optional).","Do♯ grave. WFG añade RC; varios métodos lo omiten (opcional)."),
("In 1st (5th partial) a bit flat; in 4th (6th partial) a bit sharp: 4th slightly out.","En 1.ª (5.º armónico) un poco baja; en 4.ª (6.º armónico) un poco alta: 4.ª ligeramente afuera."),
("In 2nd: 7th partial, 2nd brought in. The 4th (8th partial) is in tune.","En 2.ª: 7.º armónico, 2.ª adentro. La 4.ª (8.º armónico) está afinada."),
("In 3rd (10th partial) a bit flat: bring in slightly; in 1st (9th partial) a bit sharp.","En 3.ª (10.º armónico) un poco baja: entrar ligeramente; en 1.ª (9.º armónico) un poco alta."),
("In 3rd: 7th partial very flat, 3rd clearly brought in.","En 3.ª: 7.º armónico muy bajo, 3.ª claramente adentro."),
("In 4th (10th partial) a bit flat: bring in slightly.","En 4.ª (10.º armónico) un poco baja: entrar ligeramente."),
("In 4th: 7th partial, 4th brought in.","En 4.ª: 7.º armónico, 4.ª adentro."),
("In 5th: 5th partial, a bit flat, bring in slightly.","En 5.ª: 5.º armónico, un poco bajo, entrar ligeramente."),
("In 5th: 7th partial very flat, play 5th brought in.","En 5.ª: 7.º armónico muy bajo, tocar la 5.ª adentro."),
("In 6th: 7th partial very flat, play 6th brought in.","En 6.ª: 7.º armónico muy bajo, tocar la 6.ª adentro."),
("Left pinky F","Fa con meñique izquierdo"),
("Front F","Fa frontal (front F)"),
("Front F: left index on the front F key, middle finger on L2.","Fa frontal: índice izquierdo en la llave de fa frontal, dedo medio en L2."),
("Chromatic F♯","Fa♯ cromático"),
("Sharp: pull out the 3rd valve slide.","Alta: sacar la bomba del 3.er pistón."),
("Right index + 1st trill key; no pinky key.","Índice derecho + 1.ª llave de trino; ninguna llave de meñique."),
("Left index up.","Índice izquierdo levantado."),
("7th position (5th partial) is rarely used.","La 7.ª posición (5.º armónico) se usa poco."),
("Right 3rd finger (ring), not the index.","El 3.er dedo derecho (anular), no el índice."),
("Right pinky E","Mi con meñique derecho"),
("Same fingering as the octave below.","Misma digitación que en la octava inferior."),
("Same fingering as the octave below. Right 3rd finger (ring), not the index.","Misma digitación que en la octava inferior. El 3.er dedo derecho (anular), no el índice."),
("Same fingering as the octave below. Thumb B♭: avoid if a B natural follows. \"1 and 1\": thumb on the B key only.","Misma digitación que en la octava inferior. Si♭ de pulgar: evitar si sigue un si natural. «1 y 1»: pulgar solo en la llave de si."),
("Same fingering as C5.","Misma digitación que do5."),
("Same fingering as C♯5.","Misma digitación que do♯5."),
("Very sharp note: pull out the 3rd valve slide.","Nota muy alta: sacar la bomba del 3.er pistón."),
("No thumb or right pinky (C foot). With B foot: pinky on the \"gizmo\" key.","Sin pulgar ni meñique derecho (pata de do). Con pata de si: meñique en la llave «gizmo»."),
("No thumb or left index.","Sin pulgar ni índice izquierdo."),
("No thumb.","Sin pulgar."),
("Thumb hole open; press the register key and the A key.","Orificio del pulgar abierto; se presionan la llave de registro y la llave de la."),
("Thumb hole open. Alternative: thumb + 2 lower side keys (from/to F).","Orificio del pulgar abierto. Alternativa: pulgar + 2 llaves laterales inferiores (desde/hacia fa)."),
("Common rule: low E on the left, low F on the right.","Regla habitual: mi grave a la izquierda, fa grave a la derecha."),
("Common rule: B on the left, C on the right. Some beginner methods also hold right C (rF).","Regla habitual: si a la izquierda, do a la derecha. Algunos métodos para principiantes también mantienen do derecho (rF)."),
("SE = side E key (right hand, side).","SE = llave lateral de mi (mano derecha, lateral)."),
("Only high E♭ must be played with the right pinky.","Solo el mi♭ agudo se toca obligatoriamente con el meñique derecho."),
("Octave key only.","Solo la llave de octava."),
("Right pinky B","Si con meñique derecho"),
("Low B. Charts show RC; often closed mechanically.","Si grave. Las tablas indican RC; a menudo se cierra mecánicamente."),
("Side B♭","Si♭ lateral"),
("Thumb B♭: avoid if a B natural follows. \"1 and 1\": thumb on the B key only.","Si♭ de pulgar: evitar si sigue un si natural. «1 y 1»: pulgar solo en la llave de si."),
("Low B♭. Charts show RC (low C); on most modern saxes it already closes mechanically.","Si♭ grave. Las tablas indican RC (do grave); en la mayoría de los saxos modernos ya se cierra mecánicamente."),
("\"1 and 1\" B♭ (right index)","Si♭ «1 y 1» (índice derecho)"),
("Bis B♭: best with no B natural nearby. Also: \"1 and 1\" (L1 + R1) with F. WFG lists side B♭ as the basic fingering.","Si♭ «bis»: ideal sin si natural cerca. También: «1 y 1» (L1 + R1) con fa. WFG clasifica el si♭ lateral como digitación básica."),
("Bis B♭; also \"1 and 1\" (L1 + R1). WFG lists side B♭ as the basic fingering.","Si♭ «bis»; también «1 y 1» (L1 + R1). WFG clasifica el si♭ lateral como digitación básica."),
("Throat G: no keys (clarinet held by the right thumb).","Sol de garganta: ninguna llave (clarinete sostenido por el pulgar derecho)."),
("Tends to be sharp: pull out the 1st valve slide slightly.","Tiende a ser alta: sacar ligeramente la bomba del 1.er pistón."),
("All fingers + G♯ key + E♭.","Todos los dedos + llave de sol♯ + mi♭."),
("All open except the E♭ key (right pinky).","Todo abierto excepto la llave de mi♭ (meñique derecho)."),
("A–B♭ trill","Trino la–si♭"),
("Very sharp: pull out the 3rd valve slide.","Muy alta: sacar la bomba del 3.er pistón."),
("A bit flat (5th partial).","Un poco baja (5.º armónico)."),
]
assert len(T)==len(fr),(len(T),len(fr))
out={f:{"en":e,"es":s} for f,(e,s) in zip(fr,T)}
json.dump(out,open(sys.argv[2],'w'),ensure_ascii=False,indent=1)
print(len(out))
